{
  "comments": [
    {
      "key": {
        "uuid": "9a3d3df0_5de56536",
        "filename": "moon_wrapper/moon_wrapper/api/oslowrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 113,
      "author": {
        "id": 1384
      },
      "writtenOn": "2018-01-11T10:17:08Z",
      "side": 1,
      "message": "In fact, it is not really useful here because the returned value of this function is analyzed in line 40. And I need to send a correct response to the OpenStack connector in line 43 and not an exception. If we send an exception here (line 119), we need to catch it before sending a \"good\" response to the OpenStack connector.",
      "range": {
        "startLine": 113,
        "startChar": 9,
        "endLine": 113,
        "endChar": 22
      },
      "revId": "3b8122bb29fefe70c757a07e208081e85f06b4d0",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}