{
  "comments": [
    {
      "key": {
        "uuid": "9a3d3df0_600ed9e6",
        "filename": "python_moonutilities/python_moonutilities/exceptions.py",
        "patchSetId": 1
      },
      "lineNbr": 538,
      "author": {
        "id": 1335
      },
      "writtenOn": "2017-12-28T14:30:00Z",
      "side": 1,
      "message": "this code should be integrated with the previous check commit, because they belong to the same topic",
      "range": {
        "startLine": 538,
        "startChar": 0,
        "endLine": 538,
        "endChar": 0
      },
      "revId": "fc45140d2404d483d1d5039d9787b24de1f39164",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}